default['php-env']['date_timezone'] = 'Asia/Tokyo'
default['php-env']['display_errors'] = 'Off'
default['php-env']['display_startup_errors'] = 'Off'
default['php-env']['user'] = 'nginx'
default['php-env']['group'] = 'nginx'
